# Generated by Django 6.0.4 on 2026-06-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issue',
        ),
        migrations.DeleteModel(
            name='Reporter',
        ),
    ]
